Refactored functions logs functions
cdev-framework/cdev-sdk pull request #36
Opened 2022-06-24 13:41 UTC by lo9i

Removed duplicated code and fixed the log message

2022-06-26 01:47 UTC, DanielSanchez97 commented on src/core/default/backend.py
> +                f"Can not delete Component {component_name} in Resource State {resource_state_uuid} because the it is not empty"
change to 'because it is not empty' or leave as original

2022-06-26 02:00 UTC, DanielSanchez97 requested changes
This PR has a lot of things going on. Can you separate it into different smaller ones to make it easier to see what each change if for.

2022-06-29 19:34 UTC, DanielSanchez97 requested changes
See my one note. Besides that it looks good to me.

2022-06-29 19:35 UTC, lo9i commented on src/core/default/commands/function/logs.py
> +        cloud_client,
I'll take care of this right away

2022-06-29 21:39 UTC, DanielSanchez97 approved these changes
LGTM

2022-06-29 22:12 UTC, merged